// <auto-generated />
using System;
using ConsultasPsicologiaMVC.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsultasPsicologiaMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsultasPsicologiaMVC.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("ConsultasPsicologiaMVC.Models.ConfiguracaoHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DiasAtivos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("HoraFimAlmoco")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraFimAtendimento")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicioAlmoco")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicioAtendimento")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracaoHorarios");
                });
#pragma warning restore 612, 618
        }
    }
}
